### ISSUE TITLE
Bin 0 not analyzed in Checkm

### ISSUE THREAD

**Issue by choosehappy** [BinPro/CONCOCT#241] opened 2019-01-25 15:37 UTC
This seems related to #240 

I know that the developers of CONCOCT have used CheckM in the past to validate their results, so perhaps this is a new bug?

CONCOCT starts labeling BIN at 0 to:

![image](https://user-images.githubusercontent.com/9681868/51755349-bb507c80-20be-11e9-9c73-d6cdb4766090.png)

and produces 29 bins:
```
ajanowcz@sib-pc25:/export/big/ajanowcz/m/ea2/concoct-output$ cat clustering_merged.csv  | cut -f 2 -d , | sort | uniq -c | wc -l
29
```

When running checkm, only 28 bins are detected:
![image](https://user-images.githubusercontent.com/9681868/51755299-9a882700-20be-11e9-97f1-a6c0798d2734.png)

And Bin 0 does not appear in the output:

![image](https://user-images.githubusercontent.com/9681868/51755289-92c88280-20be-11e9-8052-e21119f451a2.png)

as well there is no bin 0 in the bin directory:

```ajanowcz@sib-pc25:/export/big/ajanowcz/m/ea2/checkm/bins$ ls
1  10  11  12  13  14  15  16  17  18  19  2  20  21  22  23  24  25  26  27  28  3  4  5  6  7  8  9
```

I can confirm this happens with at least 2 different unrelated samples.

Is this intended or is there something about bin 0? is it a "garbage" bin not intended for analysis usage?

**Comment by alneberg** [comment] 2019-01-25 15:41
Thank you @choosehappy, for a very detailed report! Can it be the extract fasta script which is the problem? Could you check whether there is a `0.fa` exported from the concoct results to begin with?

**Comment by alneberg** [comment] 2019-01-25 15:46
Sorry, what do you mean, does the concoct script `extract_fasta_bins.py` output the `0.fa` or not?

**Comment by choosehappy** [comment] 2019-01-25 15:47
it does not

![image](https://user-images.githubusercontent.com/9681868/51756215-c99f9800-20c0-11e9-9497-55f6be6e1af2.png)


![image](https://user-images.githubusercontent.com/9681868/51756242-d4f2c380-20c0-11e9-93bc-3a53b2327000.png)

**Comment by alneberg** [comment] 2019-01-25 15:48
I see, so the problem is with that script, and not with CheckM... I did some recent changes to that script. Which version of it is it that you're using?

**Comment by choosehappy** [comment] 2019-01-25 15:51
It looks like the one from October, 
id: dd180834025c66002e51a9e31440d588d0e5c183

https://github.com/BinPro/CONCOCT/commit/dd180834025c66002e51a9e31440d588d0e5c183

**Comment by alneberg** [comment] 2019-01-25 15:52
Thank you! So the extract script looks like this? https://github.com/BinPro/CONCOCT/blob/dd180834025c66002e51a9e31440d588d0e5c183/scripts/extract_fasta_bins.py

**Comment by choosehappy** [comment] 2019-01-25 15:54
you would think so, but in fact it appears to be a bit different.

i can assure you i have no modified it : )

root@5de4c4a2be1f:/opt/CONCOCT/scripts# diff extract_fasta_bins_github.py extract_fasta_bins.py
2a3
>
24,27c25,32
<         output_file = os.path.join(args.output_path, "{0}.fa".format(cluster_id))
<         seqs = [all_seqs[contig_id] for contig_id in contig_ids]
<         with open(output_file, 'w') as ofh:
<             SeqIO.write(seqs, ofh, 'fasta')
---
>         try:
>             print(contig_ids)
>             output_file = os.path.join(args.output_path, "{0}.fa".format(cluster_id))
>             seqs = [all_seqs[contig_id] for contig_id in contig_ids]
>             with open(output_file, 'w') as ofh:
>                 SeqIO.write(seqs, ofh, 'fasta')
>         except:
>             print(contig_id)

**Comment by alneberg** [comment] 2019-01-25 16:01
Hmm, strange. I cannot find any branch with that version of the file. The history of the main file does not show anything like that. How have you installed concoct? Did you use any non-standard branch?

**Comment by choosehappy** [comment] 2019-01-25 16:04
I actually have notes since i've done this in a docker image...

nothing seems out of the ordinary

```
git clone https://github.com/BinPro/CONCOCT.git
cd CONCOCT

pip2 install -r requirements.txt 
python setup.py install
nosetests
```

maybe i should git pull the latest version and try again? 

i probably should have done this originally but (a) wasn't sure if this was a concoct or checkm issue and (b) i'd need to be very careful to not destroy my data reproducibliity

**Comment by alneberg** [comment] 2019-01-25 16:06
You could try to run the github version of the `extract_fasta_bins.py` script and see if that makes a difference first?

**Comment by alneberg** [comment] 2019-01-25 16:47
Ok, that error is because of a mismatch between the new output format and the old one. The new script assumes there is not a header in the clustering file. So removing the first line of the clustering file should fix that particular error

**Comment by choosehappy** [comment] 2019-01-25 16:48
this is going to drive you crazy....but there is no header in my files:

![image](https://user-images.githubusercontent.com/9681868/51759832-682ff700-20c9-11e9-918a-c71ae8cca4d9.png)

**Comment by choosehappy** [comment] 2019-01-25 16:49
sorry, mean there isn't one in the "merged" file, but there is in the original file.

i'm only using the merged file

**Comment by alneberg** [comment] 2019-01-25 16:52
This is getting more and more exiting actually! Somehow the phrase 'contig_id' is added as a key in the `contig_ids` list...

**Comment by alneberg** [comment] 2019-01-25 16:56
I will probably not have time to look at this until monday but could you export your environment with `pip freeze` and share it here with me, please?

Otherwise if you're used to debugging python this is probably not that complicated. Somewhere here https://github.com/BinPro/CONCOCT/blob/c21349bdbe68139e82fa81dc7e14e5e8679a72a3/scripts/extract_fasta_bins.py#L18-L26 the 'contig_id' is introduced.

But yes, happy to check it out for you next week if you'd like me to.

**Comment by choosehappy** [comment] 2019-01-25 17:02
well essentially, it should be pretty straight forward to just extract the 0 fasta on its own and add it to that directory, right?

i assume the current head of this repo doesn't have this issue, so i can upgrade and use it on all further samples without any problems? 

I just don't want to have to re-do all downstream analysis for this set, as we've only noticed this discrepancy today and we've been working with the output for some time now

**Comment by alneberg** [comment] 2019-01-28 08:00
I'm afraid this seems to be an issue with the current head of the repo as well, as you just verified when trying the github version of the script? I'm suspecting it might be a difference between python 2 and python 3?

Yes, there is no magic happening in the fasta extraction script. If you're comfortable with programming you can write your own script to extract fasta files based on the clustering file.

For debugging and fixing this for other users however, it would greatly help me if I could see your python environment. Could you please supply the output of `pip freeze`?

**Comment by choosehappy** [comment] 2019-01-28 08:14
sure, see below.

if there is a general solution possible, i'm happy to help debug

```
root@5de4c4a2be1f:/data/m/ea2/concoct-output# python --version
Python 2.7.12
root@5de4c4a2be1f:/data/m/ea2/concoct-output# pip freeze
backports.functools-lru-cache==1.5
bcbio-gff==0.6.4
biopython==1.72
bz2file==0.98
certifi==2018.10.15
chardet==3.0.4
checkm-genome==1.0.14
Click==7.0
colormath==3.0.0
concoct==0.5.0
cutadapt==1.18
cycler==0.10.0
Cython==0.29
decorator==4.3.0
DendroPy==4.4.0
future==0.17.1
idna==2.7
Jinja2==2.10
kiwisolver==1.0.1
lzstring==1.0.4
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==2.2.3
multiqc==1.6
mysqlclient==1.3.13
networkx==2.2
nose==1.3.7
numpy==1.15.4
pandas==0.23.4
pyparsing==2.3.0
pysam==0.15.1
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
requests==2.20.1
scikit-learn==0.20.0
scipy==1.1.0
scour==0.32
simplejson==3.16.0
six==1.10.0
spectra==0.0.11
subprocess32==3.5.3
urllib3==1.24.1
xopen==0.3.5
```

**Comment by alneberg** [comment] 2019-01-29 11:45
Oh, that's embarrassing! Thank you for pointing it out! It should be possible to remove any such header. I'll go ahead and close this issue now. Please let me know if you run into further issues.

**Closed by alneberg** 2019-01-29 11:45 UTC
